image:
  file: .gitpod.dockerfile
vscode:
  extensions:
    - esbenp.prettier-vscode@3.11.0:dtH/6/5jWFfhGTzgegTeyg==
tasks:
  - command: >
      echo $DATABASE_NAME &&
      mkdir -p /workspace/data && mongod --dbpath /workspace/data &
