image:
  file: .gitpod.dockerfile
vscode:
  extensions:
    - esbenp.prettier-vscode@3.11.0:dtH/6/5jWFfhGTzgegTeyg==
tasks:
  - command: >
      # echo DATABASE_URL=$DATABASE_URL >> .env &&
      # echo DATABASE_NAME=$DATABASE_NAME >> .env &&
      mkdir -p /workspace/data && mongod --dbpath /workspace/data &
